### PR TITLE
fix: resolve the console warning of shader material

### PR DESCRIPTION
**Pull request by alexzhang1030**
### Why

The console will print warning messages if using `shaderMaterial`

image

Cause we use `assign` to merge `parameters` and `Three.ShaderMaterial`. There is no need to use `super(...parameters)`

### Checklist

- [ ] Documentation updated
- [x] Ready to be merged

### CODE REVIEW

**Comment by vis-prime** [comment]
typescript has no problems with this right ?

**Comment by alexzhang1030** [comment]
> typescript has no problems with this right ?

Yeah, tsc works well

**Comment by vis-prime** [comment]
i changed one `loadash.assign` to `Object.assign` should be fine right ? https://github.com/pmndrs/drei-vanilla/commit/6cda8252fc6d374802913a80c816566c97bf9143

**Comment by alexzhang1030** [comment]
> i changed one `loadash.assign` to `Object.assign` should be fine right ? [6cda825](https://github.com/pmndrs/drei-vanilla/commit/6cda8252fc6d374802913a80c816566c97bf9143)

I have merged the main branch, and no issues arose.

**Pull request merged**
