### PR TITLE
sb7

### PR DESCRIPTION
**Pull request by vis-prime**
### Why

Story book has a pop up to update itself

### What

following the updates in drei, trying to make them work here

### Checklist

- [ ] Documentation updated
- [ ] Ready to be merged

### CODE REVIEW

**Comment by vis-prime** [comment]
@abernier 

i had to install cross-env and the stotybook command was changed to

` "storybook": "cross-env NODE_OPTIONS=\"--openssl-legacy-provider\" storybook dev -p 6006",`
(also switched from npm to yarn for package managing)

it's working now but 

in setup.ts the root variable is blank
root

**Comment by abernier** [comment]
are you on a "windows" environment? I know variables-env don't behave the same...

**Comment by vis-prime** [comment]
> > i had to install cross-env and the stotybook command was changed to
> 
> are you on a "windows" environment? I know variables-env don't behave the same... (maybe cross-env helped in normalize this)

yup windows 10 x64

**Comment by abernier** [comment]
In a *nix environment, you can pass "shell-variables" before any command, like `FOO=bar ` here:

```
$ FOO=bar node -e "console.log(process.env.FOO)"
```

but this does not work exactly the same on windows... This is why you were having an error

You should probably use WSL for windows to avoiding such differences: https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by vis-prime** [comment]
> In a *nix environment, you can pass "shell-variables" before any command, like `FOO=bar ` here:
> 
> ```
> $ FOO=bar node -e "console.log(process.env.FOO)"
> ```
> 
> but this does not work exactly the same on windows... This is why you were having an error
> 
> You should probably use WSL for windows to avoiding such differences: https://learn.microsoft.com/en-us/windows/wsl/install

need to get into bios to turn on 'virtualisation' for wsl to work

but unfortunately laptop's main screen is broken

forums suggested unplugging the display ribbon so that bios shows up on the external monitor , tried that too...but no luck

can't get into bios and cannot afford to fix this right now
InShot_20230530_204510879


so putting this commit on hold for now

**Comment by abernier** [comment]
omg 😱 this issue definitely went too far...

**Comment by abernier** [comment]
otherwise if cross-env does the trick it could also be a solution

**Comment by vis-prime** [comment]
> otherwise if cross-env does the trick it could also be a solution

ohhh,...yess

the ci/codesandbox build ran correctly and i'm only using 'cross-env' for "run storybook" script,

 the `build` and `build-storybook` are still the same 
 
 interesting... sb7 is back on the menu then... 🤯🤓

**Comment by vis-prime** [comment]
re - doing this

**Pull request closed without merging**
