### PR TITLE
feat: initial storybook setup and shaderMaterial story

### PR DESCRIPTION
**Pull request by servinlp**
### Why

Add simple storybook setup to test/demo components.

### What

Add a simple (HTML) storybook setup with a story for `shaderMaterial`.

Before this gets merged there should probably be a pipeline(?)/vercel environment to showcase the storybook on and link to in the readme.

### Checklist

- [ ] Documentation updated
- [ ] Ready to be merged

### CODE REVIEW

**Comment by servinlp** [comment]
I think so, we might want to add a link to the docs like with drei but not sure how/if I can set that up

**Comment by abernier** [comment]
ok, I had a try on my machine (mac m1) and had an error while `yarn storybook`:
```sh
$ yarn storybook
yarn run v1.22.19
$ start-storybook -p 6006
info @storybook/html v6.5.16
info 
info => Loading presets

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

WARN Failed to load static files, no such directory: /Users/abernier/Sites/drei-vanilla/.storybook/public
WARN Make sure this directory exists, or omit the -s (--static-dir) option.
info => Loading custom manager config
info => Using implicit CSS loaders
info => Using default Webpack4 setup
Starting type checking service...
10% building 1/1 modules 0 activeinfo => Loading custom manager config
10% building 1/3 modules 2 active /Users/abernier/Sites/drei-vanilla/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefinednode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/abernier/Sites/drei-vanilla/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/abernier/Sites/drei-vanilla/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/abernier/Sites/drei-vanilla/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/abernier/Sites/drei-vanilla/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/abernier/Sites/drei-vanilla/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/abernier/Sites/drei-vanilla/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/abernier/Sites/drei-vanilla/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /Users/abernier/Sites/drei-vanilla/node_modules/loader-runner/lib/LoaderRunner.js:205:4 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This error seems to be kinda related to webpack 4 along node17+ according to https://github.com/storybookjs/storybook/issues/16555 and https://github.com/storybookjs/storybook/issues/16555#issuecomment-1435433626

**Comment by abernier** [comment]
ok, I've managed to upgrade to webpack5 successfully: https://github.com/pmndrs/drei-vanilla/pull/1/commits/93ac348806a2daa9dc7884a7a9f1100a13d6b846

**Comment by abernier** [comment]
I finally added the deploy task to that PR: https://github.com/pmndrs/drei-vanilla/pull/1/commits/f8c888c936ef57b33fb7056d39777abe08add325

**Pull request merged**
